# -*- coding: utf-8 -*-
"""Project 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Du_Hu3vDDtHw5qA37AWDDNpwtA9zxnNl
"""

"""
=========================================
Student Performance Analyzer
=========================================

A beginner-friendly Python project that allows users to manage
student records using a CSV file.

Features:
- Add students
- View all students
- Search students by roll number
- Update student marks
- Delete students
- Calculate grades and averages
- Find highest scorer
- Calculate pass percentage
- Sort students by average marks

Author: Maheen Jan
Language: Python
"""


import os

# ==========================
# Global Variables
# ==========================

students = []

# ==========================
# File Initialization
# ==========================

# Create the CSV file with a header if it does not already exist.
if not os.path.exists("students.csv"):
    with open("students.csv", "w") as file:
        file.write("roll_no,name,math,english,science\n")

# ==========================
# File Handling Functions
# ==========================

def load_students():
    """Loads all student records from the CSV file into the students list."""

    try:
        with open("students.csv", "r") as file:
            file.readline()  # Skip the CSV header

            for line in file:
                data = line.strip().split(",")

                students.append({
                    "roll_no": int(data[0]),
                    "name": data[1],
                    "math": int(data[2]),
                    "english": int(data[3]),
                    "science": int(data[4])
                })

    except FileNotFoundError:
        print("No file found (this should NOT happen now)")

def save_students():
  """ Saves all student records to the CSV file."""

  with open("students.csv", "w") as file:
    file.write("roll_no,name,math,english,science\n")
    for student in students:
      file.write(f"{student['roll_no']},{student['name']},{student['math']},{student['english']},{student['science']}\n")

# ==========================
# Validation Functions
# ==========================

def get_valid_marks(subject):
    """Validates that marks are between 0 and 100."""

    while True:
      try:
        marks = int(input(f"Enter {subject} marks:"))

        if 0 <= marks <= 100:
          return marks
        else:
          print("Marks must be between 0 and 100")

      except ValueError:
        print("Please enter numbers only.")

def get_valid_roll_no():
    """Validates that the roll number is 0 and positive."""

    while True:
      try:
        roll_no = int(input("Enter Roll No: "))

        if roll_no <= 0:
          print("Roll number must be greater than 0.")
          continue

        duplicate = False # Tracks whether the roll number already exists

        for student in students:
            if student["roll_no"] == roll_no:
               duplicate = True
               break
        if duplicate:
          print("Roll number already exists.")
        else:
          return roll_no

      except ValueError:
        print("Please enter numbers only.")

# ==========================
# Analysis Helper Functions
# ==========================

def calculate_average(student):
    """Calculates the average marks of a student."""

    total = student["math"]+student["english"]+student["science"]
    average = total/3
    return average

def calculate_grade(average):
    """Returns the grade based on the average marks."""

    if average >= 90:
        return "A"
    elif average >= 80:
        return "B"
    elif average >= 70:
        return "C"
    elif average >= 60:
        return "D"
    else:
        return "F"

# ============================
# Student Management Functions
# ============================

def add_student():
    """Adds a new student after validating the roll number and marks."""

    roll_no = get_valid_roll_no()

    # Keep asking until a non-empty name is entered.
    while True:
      name = input("Enter Student's name: ").strip().title()
      if name:
         break

      print("Name cannot be empty.")

    math = get_valid_marks("Math")
    english = get_valid_marks("English")
    science = get_valid_marks("Science")

    student = {
        "roll_no": roll_no,
        "name": name,
        "math": math,
        "english": english,
        "science": science
    }

    students.append(student)
    save_students()

    print("Student added successfully!")

def view_students():
    """Displays all students with their average and grade."""

    if len(students) == 0:
        print("No students found.")
        return

    for student in students:
        print("Roll No:", student["roll_no"])
        print("Name:", student["name"])
        print("Math:", student["math"])
        print("English:", student["english"])
        print("Science:", student["science"])

        average = calculate_average(student)
        print("Average:", round(average, 2))

        grade = calculate_grade(average)
        print("Grade:", grade)

        print()

def search_student():
    """Searches for a student using their roll number."""

    try:
      search_roll = int(input("Enter Roll No: "))
    except ValueError:
       print("Please enter numbers only.")
       return
    for student in students:
        if student["roll_no"] == search_roll:
            print("Roll No:", student["roll_no"])
            print("Name:", student["name"])
            print("Math:", student["math"])
            print("English:", student["english"])
            print("Science:", student["science"])
            average = calculate_average(student)
            grade = calculate_grade(average)
            print("Average:", round(average, 2))
            print("Grade:", grade)
            return

    print("Student not found.")

def update_student():
    """Updates the marks of an existing student."""

    try:
        search_roll = int(input("Enter student's roll no to update: "))
    except ValueError:
        print("Please enter numbers only.")
        return
    for student in students:
        if student["roll_no"] == search_roll:
                math = get_valid_marks("Math")
                english = get_valid_marks("English")
                science = get_valid_marks("Science")
                student["math"] = math
                student["english"] = english
                student["science"] = science

                # Save the updated records to the CSV file.
                save_students()

                print("Student updated successfully!")
                return
    print("Student not found.")

def delete_student():
    """Deletes a student using their roll number."""

    try:
        search_roll = int(input("Enter student's roll no to delete: "))
    except ValueError:
        print("Please enter numbers only.")
        return
    for student in students:
        if student["roll_no"] == search_roll:
            students.remove(student)

            # Save the updated records to the CSV file.
            save_students()

            print("Student deleted successfully!")
            return
    print("Student not found.")

# ==============================
# Reporting Functions
# ==============================

def highest_scorer():
    """Finds and displays the student with the highest total marks."""

    if len(students) == 0:
        print("No students found.")
        return

    topper = students[0]

    for student in students:
        total_student = (
            student["math"] +
            student["english"] +
            student["science"]
            )
        total_topper = (
            topper["math"] +
            topper["english"] +
            topper["science"]
            )
        if total_student > total_topper:
          topper = student
    print("\n===== Highest Scorer =====")
    print("Roll No:", topper["roll_no"])
    print("Name:", topper["name"])
    print("Math:", topper["math"])
    print("English:", topper["english"])
    print("Science:", topper["science"])

    average = calculate_average(topper)
    print("Average:", round(average, 2))
    grade = calculate_grade(average)
    print("Grade:", grade)

def pass_percentage():
    """Calculates the percentage of students who passed."""

    if len(students) == 0:
        print("No students found.")
        return
    passed = 0
    for student in students:
        average = calculate_average(student)
        grade = calculate_grade(average)
        if grade != "F":
            passed += 1
    percentage = (passed/len(students))*100

    print("\n===== Percentage of Students Passed =====")
    print("Total Students:", len(students))
    print("Students passed:", passed)
    print("Failed students:", len(students)-passed)
    print("Pass Percentage:", round(percentage, 2), "%")

def sort_students():
    """Sorts and displays students by average marks in descending order."""

    if len(students) == 0:
        print("No students found.")
        return
    sorted_students = sorted(
        students,
        key = lambda student: calculate_average(student),
        reverse = True
    )
    print("\n===== Sorted Students =====")

    rank = 1

    for student in sorted_students:
        average = calculate_average(student)
        grade = calculate_grade(average)

        print(f"{rank}. {student['name']} (Roll No: {student['roll_no']})")
        print("Math:", student["math"])
        print("English:", student["english"])
        print("Science:", student["science"])
        print("Average:", round(average, 2))
        print("Grade:", grade)
        print()

        rank += 1

# ==========================
# Main Program
# ==========================

# Load all existing student records before showing the menu.
load_students()

while True:

    print("\n===== Student Performance Analyzer =====")
    print("1. Add Student")
    print("2. View Students")
    print("3. Search Student")
    print("4. Highest Scorer")
    print("5. Pass Percentage")
    print("6. Update Student")
    print("7. Delete Student")
    print("8. Sort Students by Average")
    print("9. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_student()

    elif choice == "2":
        view_students()

    elif choice == "3":
        search_student()

    elif choice == "4":
        highest_scorer()

    elif choice == "5":
        pass_percentage()

    elif choice == "6":
        update_student()

    elif choice == "7":
        delete_student()

    elif choice == "8":
        sort_students()

    elif choice == "9":
        print("Exiting...")
        break

    else:
        print("Invalid choice. Please try again.")